# applications/argocd-ingress-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after ArgoCD
spec:
  project: default
  source:
    repoURL: 'https://github.com/mikha-22/homelab-gitops-temp.git'  # UPDATE THIS!
    targetRevision: HEAD
    path: manifests/argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
